services:
  server:
    build:
      context: .
      target: release
    # ports:
    #   - 3000:3000
    # volumes:
    #   - "/home/opc/beeMonitorContent/labs:/beeMonitorData/labs:rw"
    #   - "/home/opc/beeMonitorContent/tipizate:/beeMonitorData/tipizate:rw"
    #   - "/home/opc/beeMonitorContent/blog:/beeMonitorData/blog:rw"
    #   - "./.env:/app/.env"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.beeMonitor.rule=Host(`beemonitor.blitzcloud.me`)"
      - "traefik.http.routers.beeMonitor.entrypoints=https"
      - "traefik.http.routers.beeMonitor.tls=true"
      - "traefik.http.services.beeMonitor.loadbalancer.server.port=8030"
      #Define midleware
      - "traefik.http.routers.beeMonitor.middlewares=my-traefikBouncer@file,my-cloudflarewarp@file"
    networks:
      - proxy
    restart: always

networks:
  proxy:
    external: true
