services:
  server:
    build:
      context: .
      target: release
    # ports:
    #   - 3000:3000
    # volumes:
    #   - "/home/opc/ettihContent/labs:/ettihData/labs:rw"
    #   - "/home/opc/ettihContent/tipizate:/ettihData/tipizate:rw"
    #   - "/home/opc/ettihContent/blog:/ettihData/blog:rw"
    #   - "./.env:/app/.env"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ettih.rule=Host(`beemonitor.blitzcloud.me`)"
      - "traefik.http.routers.ettih.entrypoints=https"
      - "traefik.http.routers.ettih.tls=true"
      - "traefik.http.services.ettih.loadbalancer.server.port=8030"
      #Define midleware
      - "traefik.http.routers.ettih.middlewares=my-traefikBouncer@file,my-cloudflarewarp@file"
    networks:
      - proxy
    restart: always

networks:
  proxy:
    external: true
